x-common-env: &common-env
  ENABLE_NGINX_AUTH: 1

services:
  web:
    build: .
    expose:
      - "5000"
    environment:
      <<: *common-env
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:example@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    environment:
      <<: *common-env
      HTPASSWD_USER: ${HTPASSWD_USER}
      HTPASSWD_PASS: ${HTPASSWD_PASS}
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  pgdata: