x-common-env: &common-env
  ENABLE_NGINX_AUTH: 1

services:
  web:
    build: .
    expose:
      - "4000"
    environment:
      <<: *common-env
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
    depends_on:
      - db
    volumes:
      - ./migrations:/app/migrations

  db:
    image: postgres

    environment:
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    environment:
      <<: *common-env
      HTPASSWD_USER: ${HTPASSWD_USER}
      HTPASSWD_PASS: ${HTPASSWD_PASS}
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  pgdata: